discord:
    webhook_url: ENC[AES256_GCM,data:+ZOS75zelJrthZCfJWmfGt29xgW2ls3CpsCGFcG3V2h3rcbtFl3htIeBxyQJnZrKVEkQl5wrXam4DbcdGKRDS3tV4aUKhhvyhSgnGY3i4wmWHpnpgpV5mfIbMNYXP01/apcrePnxbSbUSCFuiSqSGrkUUZUkfNuYvQ==,iv:+JWQgq5vbsM2itYoiFSM79UxTCHYNazeUSFztM09TG0=,tag:mYzcszpdKHgq+Qn/ItVCiw==,type:str]
    user_id: ENC[AES256_GCM,data:sO2e/K7H5w/OrMJpSC68Dmkg,iv:+UgQPdcGJAtw6vaaBAzQ+LnFTfJw7/fSSHW3vB6ukGI=,tag:1jv0ldD2wh11nbBRKi+Lug==,type:str]
sops:
    age:
        - recipient: age1p057v4es63p6fef8usy67tkza7dj4xg326w5gm3c7rdthcd3xqlqps38z9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2d0JacFlPNFBTU2F6cTds
            Rk44bnI3S2lWSTZGMDJlOURIZGJjd3E0UFV3CkVlSVVUWTNDQzVxeU13VnZ4aXRl
            d0o5RElnc0MxeDdUeE9EUWhXV2QrNmMKLS0tIGg3SitBeVBaY2EwYnY2b2lBc0pn
            Y2J0UGZVbVIrK3ZmMFZGRlk1aHQ3T00K8BnxmqeBHf07HMzp+E8NO/5m5u/2alVY
            Kj0jIKqun+uClNM4t/2L5Gh6XAw8FsWkzeFgYHBI1i7xyZymwv/2rg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tuyn9u7qca3mpk082a94mnwpwgue7wlux2c7mruyxg7fz9y45qrqnqw3yx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTW1OdzhzTVNDc0xHWEdH
            alNRZUg1WExsVk43M0o2WmV5NEt6L0FvRUZ3Ck1pSEd5cHRxbERQK255M2RBT3RT
            aFY5ZkVpclUwU1dESGVhckVpbU9NQ1UKLS0tIGtFRkhiVVYrb0wrbTE5UlNRei90
            Y2JPWm5EZzJVWW55NFFRTktCeEU0dXcKSIGp8KVhOqenrK70AyBqXXkLvZ+NxvGU
            ikl6a4D9V3EfXIUVNldQhV8tU6GjzBYS2PgVf5P+l0yWLtHQxgC8SQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age124zeln7fujjzwpaeq2lmg00r93t4kp7tea684yr85prk0zh9jvfqj247af
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOa29vMFBkMGs5bmd5aktE
            ZnpDODlYYVU4K0dTNHlWZVNXOTFEblNUN2lVCjFrcWVaLzBoRk9QWWZvKzQxTXFM
            YVdLZXZBcDliSFIyY3gwWEVqTEV4d2MKLS0tIHgyTjVMZGlQRVdJWmNvckNpTmdE
            T2NiS3ZZKytzaHpjUkJLdUJYTmJRVkUKGsgC6iKasRF0we8AO2XaixfAerdr2k7P
            5QNfa4TBBVmVEZS1wPJUh5UHzDUOYOJL2Ou0AhTCXppEdZi/NNSdiA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n9tqc8fc5cecey0ca4l2kj74arzl96rnj9kqu02x7amsw2g58erqdcxfpd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcFd6UzVFMG1iQm9UWm4v
            YW5RNUt0VkNTd2xSdFFKa0F6TmsrbWQyNWtnCld5Mm1qYmZOUWcrblZkRjdjM1pP
            c0Q5c3hNMkNsUkNkV2FUbVRzQUQ3Zk0KLS0tIFlmQXZUUWV4QWU0VDByTnFUY2pM
            aUtGbUtQK0FNVG9rMCtnTEtmbW9pQ2MKVQXDfLdZ8BckTyT2qw8GKpff8XicUKKa
            2gpapn5B9AJAUuO+jK2tJ74Zmvfb5qxeDgHPKccMSUZGIIgJfTZpCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-27T05:47:55Z"
    mac: ENC[AES256_GCM,data:sehcsHNqizf/iNlJrcbNPH4rp4sY/5arb4ySwUK6mPCXm7Woqi7a1Cva4LyorCqrHWGxyLmKj9ZqetjNs0Kb7W4fA3lpQMMMMy45ox+alvyyAzskDg+hz0zSx3wSZHTdShxqiwdbVUPW3C7sk0p/bG4OaxnlG8Fv/SJyWpA4W9E=,iv:5Bh4f3nWeWF6rl7kSiTZvlvaqiokTdO2EiBoHiD+Q0w=,tag:8phwxN3fSek19Jvc9u31bQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
